force-app/main/default/objects/credit_card_debt__c/credit_card_debt__c.object-meta.xml
<CustomObject>
    <label>credit card debt</label>
    <nameField>
        <label>credit card debt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>credit card debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/credit_card_debt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>credit card debts</relationshipLabel>
    <relationshipName>credit_card_debts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/credit_card_debt__c/fields/dias_mora__c.field-meta.xml
<CustomField>
    <fullName>dias_mora__c</fullName>
    <label>dias mora</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/credit_card_debt__c/fields/monto_vencido__c.field-meta.xml
<CustomField>
    <fullName>monto_vencido__c</fullName>
    <label>monto vencido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/credit_card_debt__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <label>product</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CarteraVencidaController.cls
public with sharing class CarteraVencidaController {
 
@AuraEnabled
public static List<credit_card_debt__c> getCreditCard(String accountId){
    List<credit_card_debt__c> listCreditCard = [SELECT Id, Name, 
                                                Status__c, product__c, Monto_original__c,
                                                monto_vencido__c,Fecha_emision__c,
                                                Fecha_vencimiento__c, dias_mora__c, 
                                                observation__c, Account__c 
                                                from credit_card_debt__c
                                                WHERE Account__c=:accountId AND
                                                Status__c = 'Open' AND dias_mora__c > 1];

    return listCreditCard;
}

@AuraEnabled
public static void saveObservacion(String creditCarId, String observacionUpdate){
    credit_card_debt__c creaditObj = [SELECT Id,observation__c from credit_card_debt__c WHERE Id=:creditCarId];
    creaditObj.observation__c = observacionUpdate;
    try {
        update creaditObj;
    } catch (Exception e) {
        
    }
}

}